name: github-script-add-comment Workflow

on:
    issues:
        types: [closed]

permissions:
    contents: read
    issues: write
    pull-requests: write

jobs:
    gh-script-comment:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/github-script@v6
          with:
            script: |
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "The issue is closed. I'm making a comment from `actions/github-script`!"
              })
