name: Secret Workflow

on: push

jobs:
    secrets:
        runs-on: ubuntu-latest
        steps:
        -   name: Print length of a secret
            run: |
                import os
                print(len(os.getenv('MY_SECRET_VAR')))
            shell: python
            env:
                MY_SECRET_VAR: ${{ secrets.MY_SECRET }}
